[package]
name = "canonnibot"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
html-escape = "0.2.13"
mwbot = "0.6.1"
regex = "1.11.1"
tokio = { version = "1.45.1", features = ["full"] }
